[workspace]
authors = ["Byron"]
channels = ["conda-forge"]
name = "typescript-practice"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
update-nodejs = "npm install --save"
setup-tsc = 'tsc --init --outDir "jsFiles" --rootDir "tsFiles" --sourceMap'
compile-ts = "tsc"
watch-ts = "tsc --noEmit --watch"
serve-dev = "(pixi run watch-ts &) && (npm run dev &)"

[dependencies]
nodejs = ">=25.2.1,<25.3"
